/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.unprg.view;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pe.edu.unprg.controller.UsuarioJpaController;
import pe.edu.unprg.entity.Usuario;

/**
 *
 * @author asus
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    //
    private UsuarioJpaController ejc = new UsuarioJpaController ();
    private Usuario usuario; 
    
    public LoginFrame() {
        initComponents();
      //para la imagen de fondo
        //para afirmar las dimenciones 
        setSize(400,550);
        //para que no pueda modificar el tamaño de la pantalla
        setResizable(false);
        //titulo de la interfase
        setTitle("Acceso al sistema");
        //centrar en la pantalla
        setLocationRelativeTo(null);
        //agregar imagen y escalarla 
            //crear objeto 
        ImageIcon wallpaper = new ImageIcon("src/pe/edu/unprg/images/fondo11.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_fondo.getWidth(), 
                            jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_fondo.setIcon(icono);
        this.repaint();
        
       //para el log de usuario
        ImageIcon wallpaper_logo = new ImageIcon("src/pe/edu/unprg/images/LOGO_3.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(jLabel1_usuario.getWidth(), 
                            jLabel1_usuario.getHeight(), Image.SCALE_DEFAULT));
        //colocar la imagen dentro del jlabel
        jLabel1_usuario.setIcon(icono_logo);
        this.repaint();
    }
    
    //para el icono 
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("pe/edu/unprg/images/LOGO_3.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_usuario = new javax.swing.JLabel();
        txt_contra = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(400, 550));
        setPreferredSize(new java.awt.Dimension(400, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 220, 220));

        txt_contra.setBackground(new java.awt.Color(153, 153, 255));
        txt_contra.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txt_contra.setForeground(new java.awt.Color(153, 255, 255));
        txt_contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_contra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_contra.setSelectionColor(new java.awt.Color(102, 255, 255));
        getContentPane().add(txt_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 310, 210, -1));

        txt_usuario.setBackground(new java.awt.Color(153, 153, 255));
        txt_usuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 250, 210, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Acceder");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 380, 210, 35));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{ 
        PrincipalFrame pf = new PrincipalFrame();
        usuario = ejc.findByUsernameAndPassword(txt_usuario.getText(), txt_contra.getText());
        if (usuario != null ) {
            dispose();
            pf.setVisible(true);
            
        }else {
            JOptionPane.showMessageDialog(null, "Usuario no válido", "Advertenica", JOptionPane.WARNING_MESSAGE);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error en el sistema", "Advertenica", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1_usuario;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JPasswordField txt_contra;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
